version: '3.1'

services:
  otus-db:
    container_name: otus-postgres
    image: postgres:10.5-alpine
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - private
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  otus-rabbitmq:
    container_name: otus-rabbitmq
    image: rabbitmq:3.7.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
      RABBITMQ_DEFAULT_VHOST: '${RABBITMQ_DEFAULT_VHOST}'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - private

volumes:
  pgdata:
    external: false

networks:
  private:
    driver: bridge